// coisas que ele ama nela.
// (também editável pelo painel admin > Textos)

import { applyOverride } from './content-overrides.js';

const DEFAULT = [
  { emoji: '🌅', text: 'amo seu jeito lento de acordar', sub: 'até por que com isso eu acordo lento também' },
  { emoji: '☕', text: 'amo que você lembre coisas que eu nem cheguei a dizer', sub: 'como se já tivesse me ouvido em outra vida' },
  { emoji: '😂', text: 'amo a sua risada quando só você acha graça', sub: 'por causa dela eu do risada também' },
  { emoji: '🌧️', text: 'amo dia ruim, se for com você', sub: 'tempo de chuva só é deprimente para quem não tem uma Luana' },
  { emoji: '🤔', text: 'amo as perguntas que você faz', sub: 'mesmo as contrangedoras kk' },
  { emoji: '🐾', text: 'amo como você fala com os bichos da casa', sub: 'cada um ganha um tom seu' },
  { emoji: '🌸', text: 'amo sua memória que guarda partes minhas', sub: 'que eu nem sabia que tinha' },
  { emoji: '💛', text: 'amo você sendo só você', sub: 'sem editar pra ninguém, nem pra mim' },
  { emoji: '👁️', text: 'amo seus olhos', sub: 'têm uma profundidade que eu ainda não terminei de ler' },
  { emoji: '🤲', text: 'amo suas mãos', sub: 'a forma como elas seguram as coisas — e como me seguram' },
  { emoji: '🌺', text: 'amo seu cheiro', sub: 'é o único lugar onde me sinto completamente em casa' },
  { emoji: '🎵', text: 'amo sua voz', sub: 'fala e já é música, mesmo sem querer' },
  { emoji: '😴', text: 'amo você dormindo', sub: 'parece que o mundo inteiro para de te cobrar e você é só paz' },
  { emoji: '🍽️', text: 'amo quando você come algo gostoso', sub: 'a reação de milhões "Will you marry me"' },
  { emoji: '🌙', text: 'amo as noites quietas do seu lado', sub: 'sem fazer nada, sem precisar de nada' },
  { emoji: '🧠', text: 'amo como você pensa', sub: 'não linear, não previsível — completamente você' },
  { emoji: '💬', text: 'amo como você conta uma história', sub: 'com detalhes que ninguém mais perceberia que importam' },
  { emoji: '🌿', text: 'amo seu cuidado com as coisas vivas', sub: 'planta, bicho, gente — você trata tudo como se fosse sagrado (apesar das plantas não acharem isso)' },
  { emoji: '🎨', text: 'amo seu gosto', sub: 'pelas cores, pelos tecidos, pelo jeito que você monta um ambiente' },
  { emoji: '🛌', text: 'amo quando você se aconchega', sub: 'aquele gesto de se atirar na cama e fazer sons estranhos' },
  { emoji: '😊', text: 'amo seu sorriso tímido', sub: 'o de quando você fica com vergonha mas não consegue esconder (ai esconde a cara olhando pra baixo)' },
  { emoji: '🤣', text: 'amo quando você ri de algo idiota', sub: 'e eu nem preciso saber do que é pra rir junto' },
  { emoji: '🌊', text: 'amo sua calma', sub: 'não é ausência de sentimento — é força que não precisa gritar' },
  { emoji: '🧩', text: 'amo como você resolve problemas', sub: 'tranquila por fora, fervilhando por dentro, saindo com a resposta certa' },
  { emoji: '📚', text: 'amo sua curiosidade', sub: 'você pergunta sobre o mundo como se ele fosse sempre novo' },
  { emoji: '🌻', text: 'amo seu otimismo quieto', sub: 'você não faz alarde — só acredita, e isso muda o ambiente' },
  { emoji: '🍦', text: 'amo suas preferências', sub: 'as coisas específicas que você gosta e só você tem razão de gostar (assassinos asiáticos)' },
  { emoji: '🐱', text: 'amo como os bichos te escolhem', sub: 'animais sabem de coisas que a gente ainda está aprendendo' },
  { emoji: '💤', text: 'amo sua respiração quando dorme do meu lado', sub: 'é o metrônomo da melhor parte do final de semana' },
  { emoji: '🌈', text: 'amo quando você para pra olhar pro céu', sub: 'como se o céu fosse uma mensagem e você fosse a única que entende' },
  { emoji: '🤗', text: 'amo seu abraço', sub: 'tem um jeito específico de apertar que parece dizer estou aqui' },
  { emoji: '🎤', text: 'amo quando você canta baixinho', sub: 'sem perceber, sem público, só você e a música' },
  { emoji: '🍕', text: 'amo dividir comida com você', sub: 'você sempre deixa o melhor pedaço pra mim sem avisar' },
  { emoji: '📱', text: 'amo quando você me manda coisa aleatória', sub: 'um meme, um vídeo bobo — é você pensando em mim no meio do dia' },
  { emoji: '🌄', text: 'amo acordar antes de você às vezes', sub: 'só pra te ver dormindo sem saber que estou olhando' },
  { emoji: '🧸', text: 'amo seu lado criança que não some', sub: 'a leveza de ainda se divertir com coisa boba' },
  { emoji: '💪', text: 'amo sua força', sub: 'a que você exerce sem perceber e sem precisar de aplauso' },
  { emoji: '🌝', text: 'amo seu humor de madrugada', sub: 'quando você fica estranha e engraçada de um jeito que é só seu' },
  { emoji: '🦋', text: 'amo como você muda sem se perder', sub: 'cresce, evolui, mas continua você de um jeito que eu reconheço' },
  { emoji: '🎯', text: 'amo sua intuição', sub: 'você acerta as coisas antes de ter dados pra acertar' },
  { emoji: '🌍', text: 'amo sua visão de mundo', sub: 'mais justa, do que a maioria das pessoas consegue ser' },
  { emoji: '🧶', text: 'amo seu jeito de cuidar', sub: 'não é performance — é você mesmo, vazando por todos os lados' },
  { emoji: '🎭', text: 'amo suas expressões faciais', sub: 'você pensa que está sendo discreta mas o rosto entrega tudo' },
  { emoji: '🍃', text: 'amo seu silêncio', sub: 'não é frio, não é distância — é presença de outro tipo' },
  { emoji: '🌟', text: 'amo quando você fica animada', sub: 'os olhos brilham mais rápido que você consegue esconder' },
  { emoji: '🧘', text: 'amo seu equilíbrio', sub: 'você encontra o chão quando tudo está balançando' },
  { emoji: '💌', text: 'amo como você demonstra amor', sub: 'nos gestos pequenos que só eu sei identificar' },
  { emoji: '🌮', text: 'amo comer com você qualquer coisa', sub: 'até coisa comum vira programa quando é do seu lado' },
  { emoji: '🔒', text: 'amo a segurança que sinto com você', sub: 'não preciso fingir nem me proteger — só existir' },
  { emoji: '🎁', text: 'amo como você escolhe presentes', sub: 'com aquele detalhe que prova que esteve prestando atenção o tempo todo' },
  { emoji: '🌙', text: 'amo suas teorias sobre as coisas', sub: 'sempre têm uma lógica torta e perfeita que eu nunca teria' },
  { emoji: '🦊', text: 'amo sua esperteza suave', sub: 'você chega onde quer sem atropelar ninguém' },
  { emoji: '💫', text: 'amo sua teimosia quando é por algo que importa', sub: 'você não cede em coisa errada — isso é raro e precioso' },
  { emoji: '🎶', text: 'amo sua relação com música', sub: 'como uma letra te encontra exatamente quando você precisa' },
  { emoji: '🖐️', text: 'amo seu toque', sub: 'sabe quando é pra acalmar, quando é pra chamar atenção, quando é só amor' },
  { emoji: '🌱', text: 'amo sua paciência', sub: 'com as coisas que crescem devagar, inclusive comigo' },
  { emoji: '🏠', text: 'amo que você transformou o nosso espaço num lar', sub: 'sem anunciar, foi colocando você em cada canto' },
  { emoji: '☀️', text: 'amo você de manhã de domingo', sub: 'sem pressa, sem compromisso, só existindo no tempo dela' },
  { emoji: '🫂', text: 'amo quando você chega perto sem falar nada', sub: 'às vezes presença é o idioma mais completo' },
  { emoji: '🎠', text: 'amo sua imaginação', sub: 'transforma o cotidiano em algo que vale a pena ser contado' },
  { emoji: '🌒', text: 'amo você nos dias de introversão', sub: 'quando está mais pra dentro e o mundo fica de fora' },
  { emoji: '💎', text: 'amo sua honestidade', sub: 'você fala a verdade com cuidado, sem crueldade' },
  { emoji: '🦁', text: 'amo sua coragem discreta', sub: 'vai em frente mesmo com medo, sem fazer drama disso' },
  { emoji: '🌸', text: 'amo como você trata as pessoas', sub: 'com atenção real, não de protocolo' },
  { emoji: '🎀', text: 'amo seu feminino', sub: 'que é delicado e poderoso ao mesmo tempo' },
  { emoji: '🍂', text: 'amo você na mudança de estação', sub: 'como você percebe antes dos outros que algo mudou no ar' },
  { emoji: '🖼️', text: 'amo seu olho pra beleza', sub: 'você enxerga arte onde a maioria passa direto' },
  { emoji: '🧁', text: 'amo quando você faz algo com as mãos', sub: 'tem um prazer no processo que contamina a sala inteira' },
  { emoji: '🌀', text: 'amo sua complexidade', sub: 'você não é simples e isso é o que me mantém descobrindo' },
  { emoji: '🕊️', text: 'amo a paz que você traz', sub: 'não a paz de ausência só paz' },
  { emoji: '🎲', text: 'amo quando você topa o imprevisto', sub: 'plano muda, você adapta, segue em frente sem reclamar' },
  { emoji: '🌙', text: 'amo seu olhar de curiosidade', sub: 'quando algo novo aparece e os olhos acendem antes da palavra' },
  { emoji: '🫶', text: 'amo como você me ama', sub: 'com constância, com detalhe, com algo que parece escolha renovada todo dia' },
  { emoji: '🌺', text: 'amo seu jeito de se arrumar', sub: 'o ritual todo, a concentração, o resultado que sempre valeu a pena' },
  { emoji: '🍋', text: 'amo seu humor ácido na hora certa', sub: 'aquele comentário certeiro que só você faria' },
  { emoji: '🏔️', text: 'amo sua profundidade', sub: 'dá pra mergulhar em você e ainda não ter chegado no fundo' },
  { emoji: '🎸', text: 'amo sua intensidade com as coisas que gosta', sub: 'vai fundo, sem meio-termo, com aquele brilho de quem realmente vive' },
  { emoji: '🍀', text: 'amo sua leveza', sub: 'não é superficialidade — é a leveza de quem escolheu não carregar o desnecessário' },
  { emoji: '🎪', text: 'amo quando você fica empolgada', sub: 'fala mais rápido, gesticula mais, e o quarto fica maior' },
  { emoji: '🌊', text: 'amo sua resiliência', sub: 'dobra, mas não quebra — e volta diferente, não menor' },
  { emoji: '🧿', text: 'amo sua percepção das pessoas', sub: 'você lê quem está bem e quem não está, antes de qualquer palavra' },
  { emoji: '🎋', text: 'amo como você se adapta', sub: 'sem perder a essência, só mudando o que precisa mudar' },
  { emoji: '🌙', text: 'amo conversar com você de noite', sub: 'a versão noturna sua é ainda mais honesta' },
  { emoji: '🦢', text: 'amo sua elegância natural', sub: 'não é postura — é uma graça que sai de dentro' },
  { emoji: '🎯', text: 'amo sua objetividade quando importa', sub: 'corta o ruído, vai ao ponto, diz o que precisa ser dito' },
  { emoji: '🌿', text: 'amo sua gentileza com estranhos', sub: 'um sorriso pra quem precisava e você nem sabe que deu' },
  { emoji: '🌠', text: 'amo seus sonhos', sub: 'os que você conta de manhã e os que guarda só pra você' },
  { emoji: '🎡', text: 'amo sua nostalgia', sub: 'você guarda memórias com carinho, como quem sabe que um dia vai querer rever' },
  { emoji: '🍯', text: 'amo sua doçura', sub: 'não é mel de fachada — é doçura que sustenta' },
  { emoji: '🌪️', text: 'amo sua intensidade nos momentos certos', sub: 'quando decide, decide inteiro — não tem meias medidas' },
  { emoji: '🧲', text: 'amo a forma como você me atrai', sub: 'mesmo depois de tanto tempo, ainda sinto aquilo' },
  { emoji: '🌞', text: 'amo você feliz', sub: 'quando está bem, o ambiente inteiro muda de tom' },
  { emoji: '🎠', text: 'amo sua memória afetiva', sub: 'guarda datas, detalhes, como se cada lembrança fosse um tesouro' },
  { emoji: '🍁', text: 'amo seu jeito de deixar ir', sub: 'o que não serve mais, você solta sem dramaturgia' },
  { emoji: '🌌', text: 'amo como você me faz sentir especial', sub: 'não com palavras grandes — com atenção real no dia a dia' },
  { emoji: '🐝', text: 'amo sua produtividade silenciosa', sub: 'quando entra no modo foco, o mundo pode estar pegando fogo lá fora' },
  { emoji: '🌷', text: 'amo seu perfume', sub: 'aprendi a associar a sensação de chegou com esse cheiro' },
  { emoji: '🏡', text: 'amo construir coisas com você', sub: 'planos, rotinas, memórias — cada tijolo colocado junto' },
  { emoji: '🎵', text: 'amo quando você associa música a memórias', sub: 'aquela habilidade de virar no tempo por causa de uma nota' },
  { emoji: '🧸', text: 'amo sua ternura com crianças', sub: 'fica mais suave, mais devagar — como se soubesse que elas merecem isso' },
  { emoji: '🍫', text: 'amo suas fraquezas', sub: 'as preferências que você não consegue negar e nem tenta' },
  { emoji: '🔑', text: 'amo que você me conhece', sub: 'às vezes melhor do que eu mesmo, e não usa isso contra mim' },
  { emoji: '🌻', text: 'amo seu otimismo com o futuro', sub: 'mesmo sem garantia, você acredita que vai ser bom' },
  { emoji: '🎐', text: 'amo o movimento que você traz', sub: 'a casa respira diferente quando você está nela' },
  { emoji: '💡', text: 'amo suas ideias', sub: 'surgem do nada, no meio de outro assunto, e sempre têm algo de genial' },
  { emoji: '🛁', text: 'amo seu ritual de autocuidado', sub: 'o jeito que você presta atenção em si mesma' },
  { emoji: '🎭', text: 'amo suas mil facetas', sub: 'tem uma versão sua pra cada hora do dia, e eu quero conhecer todas' },
  { emoji: '🌙', text: 'amo que você não desiste das pessoas', sub: 'mesmo quando teria razão de desistir' },
  { emoji: '🍃', text: 'amo seu respeito pela natureza', sub: 'um cuidado quase instintivo com o que é vivo' },
  { emoji: '🫀', text: 'amo sua lealdade', sub: 'quando está do seu lado, está de verdade — não tem condição escondida' },
  { emoji: '🌈', text: 'amo sua diversidade interna', sub: 'tem profundidade onde ninguém esperaria e leveza onde ninguém acredita que cabe' },
  { emoji: '⚡', text: 'amo sua energia nos dias bons', sub: 'aquele estado de liga que contamina tudo ao redor' },
  { emoji: '🧊', text: 'amo sua objetividade nos momentos difíceis', sub: 'quando o emocional poderia dominar, você ainda pensa com clareza' },
  { emoji: '🌸', text: 'amo seus gestos pequenos', sub: 'arrumar a cama que eu dormi, guardar minha xícara, lembrar o que eu prefiro, me trazer uma água' },
  { emoji: '🦋', text: 'amo como você se transforma', sub: 'cada versão nova de você ainda tem o mesmo núcleo que eu me apaixonei' },
  { emoji: '🌺', text: 'amo sua presença física', sub: 'quando você entra num lugar, ele fica diferente' },
  { emoji: '🏄', text: 'amo sua adaptabilidade', sub: 'surfar o que vem em vez de lutar contra a maré' },
  { emoji: '🌙', text: 'amo quando você fica na sua', sub: 'recarregando, quieta, sem dever nada pra ninguém' },
  { emoji: '🎀', text: 'amo seu lado detalhista', sub: 'percebe o que mudou no ambiente antes de todo mundo' },
  { emoji: '🌝', text: 'amo sua ironia sutil', sub: 'aquele comentário que parece inocente mas tem um segundo plano genial' },
  { emoji: '🧩', text: 'amo como você encaixa na minha vida', sub: 'não forçado — naturalmente, como se sempre houvesse o espaço certo' },
  { emoji: '💬', text: 'amo sua comunicação', sub: 'sabe quando falar, sabe quando calar, sabe exatamente o que pesa em cada um' },
  { emoji: '🌿', text: 'amo sua consciência', sub: 'pensa nas consequências antes de agir, sem ser paralisada por elas' },
  { emoji: '🫁', text: 'amo respirar o mesmo ar que você', sub: 'divide comigo o espaço com uma generosidade que talvez nem perceba' },
  { emoji: '🎯', text: 'amo seu foco', sub: 'quando quer algo, vai com tudo — sem dispersar, sem recuar' },
  { emoji: '🔭', text: 'amo sua visão de longo prazo', sub: 'planta árvore cuja sombra pode demorar, mas acredita que vai chegar lá (metafora)' },
  { emoji: '🌸', text: 'amo quando você toma decisão', sub: 'com aquela firmeza calma de quem pesou tudo internamente' },
  { emoji: '🏰', text: 'amo sua consistência', sub: 'você é a mesma pessoa ontem, hoje e amanhã — dá pra confiar nisso' },
  { emoji: '🌙', text: 'amo suas reflexões antes de dormir', sub: 'compartilha o que ficou no dia como quem deposita no cofre mais seguro' },
  { emoji: '🎆', text: 'amo sua alegria genuína', sub: 'quando acontece algo bom, você celebra de verdade, sem moderar' },
  { emoji: '🧭', text: 'amo seu senso moral', sub: 'sabe o que é certo sem precisar de regra — vem de dentro' },
  { emoji: '💐', text: 'amo receber seu cuidado', sub: 'tem um jeito único de cuidar que não infantiliza e não invade' },
  { emoji: '🌊', text: 'amo sua profundidade emocional', sub: 'sente fundo, processa com cuidado, não desperdiça o que sente' },
  { emoji: '🦅', text: 'amo sua independência', sub: 'não precisa de mim pra ser inteira — e por isso nossa união é escolha' },
  { emoji: '🎋', text: 'amo sua flexibilidade sem fraqueza', sub: 'dobra no vento mas as raízes não saem do lugar' },
  { emoji: '🌹', text: 'amo quando você se permite', sub: 'um prazer, um descanso, um mimo — sem justificar' },
  { emoji: '🧡', text: 'amo sua capacidade de perdão', sub: 'não acumula, não reconta, não usa como munição' },
  { emoji: '🌙', text: 'amo sua presença nas noites de insônia', sub: 'mesmo dormindo, tem algo em você que acalma' },
  { emoji: '🍀', text: 'amo sua gratidão', sub: 'percebe o que tem antes de listar o que falta' },
  { emoji: '🌸', text: 'amo quando você chora e bota pra fora', sub: 'é você inteira sentindo — não tem como não amar isso' },
  { emoji: '🎠', text: 'amo suas memórias da infância', sub: 'as que você compartilha com aquele brilho de quem ainda mora lá' },
  { emoji: '🔓', text: 'amo como você me abriu (la ele)', sub: 'fui chegando, fui me permitindo, e não me arrependo de nenhum milímetro' },
  { emoji: '🌺', text: 'amo sua autoconfiança nos dias certos', sub: 'quando você sabe que sabe, não tem quem tire' },
  { emoji: '🌙', text: 'amo seu jeito de voltar pra casa', sub: 'a sequência de chegar que virou roteiro que eu memorizo com carinho' },
  { emoji: '🎵', text: 'amo dançar com você', sub: 'mesmo sem coreografia, mesmo sem ritmo, mesmo no meio da sala' },
  { emoji: '🌿', text: 'amo sua conexão com o silêncio', sub: 'não se sente na obrigação de preencher tudo — deixa o silêncio existir' },
  { emoji: '💛', text: 'amo sua leveza com as coisas materiais', sub: 'sabe separar o que tem valor do que só parece ter' },
  { emoji: '🌙', text: 'amo quando você diz meu nome', sub: 'tem um tom específico que não existe em mais nenhuma voz' },
  { emoji: '🎪', text: 'amo sua espontaneidade', sub: 'quando solta o planejamento e só vai — é quando você brilha mais' },
  { emoji: '🧿', text: 'amo sua proteção', sub: 'cuida de quem ama com uma discrição que parece magia' },
  { emoji: '🌱', text: 'amo sua vontade de crescer', sub: 'não está satisfeita só com o que é — quer mais e melhor, pra você e pra nós' },
  { emoji: '🌙', text: 'amo o que você faz com meu coração', sub: 'suaviza, expande, organiza — sem que eu precise pedir' },
  { emoji: '🎯', text: 'amo sua determinação', sub: 'não é teimosia — é clareza de quem sabe o que quer e vai buscar' },
  { emoji: '🌸', text: 'amo seu senso de humor', sub: 'inteligente, preciso e pesado kkkkk' },
  { emoji: '🌊', text: 'amo como você me acalma', sub: 'sem fazer nada extraordinário — só sendo você ao lado' },
  { emoji: '🧘', text: 'amo seu autoconhecimento', sub: 'sabe de si com uma honestidade que poucas pessoas têm coragem de ter' },
  { emoji: '🎆', text: 'amo sua presença nas datas especiais', sub: 'hoje só são especiais se você estiver comigo' },
  { emoji: '🌺', text: 'amo sua generosidade', sub: 'doa tempo, atenção e carinho sem fazer conta' },
  { emoji: '🦢', text: 'amo seu andar', sub: 'tem um ritmo específico que eu reconheço sem precisar olhar' },
  { emoji: '🌙', text: 'amo quando você está animada com um plano', sub: 'o jeito que você organiza e antecipa com alegria de criança' },
  { emoji: '🌿', text: 'amo sua leveza emocional', sub: 'processa, sente, resolve — não carrega mais do que precisa' },
  { emoji: '🔮', text: 'amo sua intuição sobre nós', sub: 'sente quando algo precisa de atenção antes de eu perceber' },
  { emoji: '🏡', text: 'amo a rotina que construímos', sub: 'cada hábito pequeno que juntos virou tradição' },
  { emoji: '🌟', text: 'amo sua luz', sub: 'não a que você mostra pro mundo — a que fica acesa quando está só' },
  { emoji: '🌺', text: 'amo você em dias de festa', sub: 'a energia, o cuidado, o prazer genuíno de estar com gente' },
  { emoji: '🍵', text: 'amo você em dias de quietude', sub: 'com cobertor, o tempo passando devagar e filme' },
  { emoji: '🌙', text: 'amo como você recebe afeto', sub: 'não deflexiona, não minimiza — recebe, agradece, fica' },
  { emoji: '🎭', text: 'amo sua sensibilidade com arte', sub: 'uma música, um livro, um quadro — chega em você de um jeito que é raro' },
  { emoji: '💫', text: 'amo como você inspira', sub: 'não sei quando acontece, mas eu me torno mais eu quando estou com você' },
  { emoji: '🌸', text: 'amo sua beleza', sub: 'a que todo mundo vê e a que só eu conheço' },
  { emoji: '🌊', text: 'amo quando você chora de rir', sub: 'limpando o olho, sem conseguir parar — é a versão mais pura sua' },
  { emoji: '🧡', text: 'amo sua coragem de ser vulnerável', sub: 'mostra o que dói sem usar isso como fraqueza' },
  { emoji: '🌙', text: 'amo a versão você-cansada', sub: 'quando baixa a guarda completamente e aparece a mais honesta de todas' },
  { emoji: '🌸', text: 'amo tudo que você me ensinou', sub: 'sobre calma, sobre cuidado, sobre como habitar melhor o mundo' },
  { emoji: '🌈', text: 'amo ter você como companheira de vida', sub: 'não porque é fácil — mas porque com você até o difícil vale a pena' },
  { emoji: '🫀', text: 'amo você', sub: 'inteira, em todos os dias, em todas as versões — agora e pra sempre' },
  { emoji: '🌙', text: 'amo quando você me corrige com gentileza', sub: 'sem humilhar, sem ironizar — só coloca no lugar certo' },
  { emoji: '🎈', text: 'amo sua leveza nos dias comuns', sub: 'transforma terça-feira à tarde em algo que vale ser lembrado' },
  { emoji: '🌿', text: 'amo como você cuida do que é nosso', sub: 'com atenção de quem sabe que é precioso sem precisar anunciar' },
  { emoji: '🍊', text: 'amo seu temperamento', sub: 'tem calor sem queimar, tem firmeza sem endurecer' },
  { emoji: '🌙', text: 'amo sua maneira de discordar', sub: 'diz o que pensa sem transformar em campo de batalha' },
  { emoji: '🎋', text: 'amo sua maturidade emocional', sub: 'não culpa o outro pelo que é seu, não cobra o que não foi combinado' },
  { emoji: '🌺', text: 'amo seu compromisso', sub: 'quando fala que vai fazer, faz — sem precisar de cobranças' },
  { emoji: '🦋', text: 'amo sua leveza com o imperfeito', sub: 'aceita que as coisas podem ser incompletas e ainda assim bonitas' },
  { emoji: '🌊', text: 'amo como você processa as coisas', sub: 'leva pra dentro, vira e revira, sai com mais clareza do que entrou' },
  { emoji: '🍃', text: 'amo sua relação com o tempo', sub: 'não apressa o que não precisa ser apressado' },
  { emoji: '🌙', text: 'amo que você me escolheu', sub: 'e que continua escolhendo, todo dia, sem fazer alarme disso' },
  { emoji: '🌸', text: 'amo o futuro que imagino com você', sub: 'não sei os detalhes, mas sei que quero você em cada cena' },
  { emoji: '💛', text: 'amo a vida que a gente está construindo', sub: 'tijolo por tijolo, dia por dia, com você do meu lado' },
  { emoji: '🌟', text: 'amo você mais do que saberia explicar', sub: 'as palavras chegam perto, mas você é maior do que elas' },
  { emoji: '🎯', text: 'amo que você é minha pessoa', sub: 'a que eu ligo primeiro, a que eu quero contar, a que faz sentido' },
  { emoji: '🌈', text: 'amo cada versão que você ainda vai ser', sub: 'e já te amo agora, sem precisar saber quem virá' },
  { emoji: '🫶', text: 'amo a gente', sub: 'o que somos juntos é algo que nenhum de nós seria sozinho' },
  { emoji: '🌙', text: 'amo adormecer do seu lado', sub: 'é o jeito mais bonito de terminar qualquer dia' },
  { emoji: '💫', text: 'amo acordar e saber que você está aqui', sub: 'essa certeza simples é uma das maiores da minha vida' },
  { emoji: '❤️', text: 'amo cada segundo que já vivemos', sub: 'e mal posso esperar pelos que ainda vêm' },
];

export const LOVES = applyOverride('loves', DEFAULT);
