// Atribuição fixa de faixas por tela. Editável pelo painel admin → aba Músicas.

export const MUSIC_DEFAULTS = {
  gate:          'lua-pegado',
  welcome:       'beautiful-things',
  loves:         'iris',
  game:          'cruel-summer',
  puzzle:        'clocks',
  final:         'memories',
  'timeline-01': 'amor-e-fe-acustico',
  'timeline-02': 'ceu-azul',
  'timeline-03': 'choose-me',
  'timeline-04': 'bem',
  'timeline-05': 'let-me-love-you',
  'timeline-06': 'lighter',
  'timeline-07': 'blinding-lights',
  'timeline-08': 'numb',
  'timeline-09': 'infinity',
  'timeline-10': 'in-the-end',
  'timeline-11': 'too-sweet',
  'timeline-12': 'ceilings',
  'timeline-13': 'somebody-that-i-used-to-know',
};

export const POOL = [
  'amor-e-fe-acustico',
  'beautiful-things',
  'bem',
  'blinding-lights',
  'boulevard-of-broken-dreams',
  'ceu-azul',
  'ceilings',
  'choose-me',
  'clocks',
  'cruel-summer',
  'infinity',
  'in-the-end',
  'iris',
  'let-me-love-you',
  'lighter',
  'lua-pegado',
  'memories',
  'mystery-of-love',
  'numb',
  'radioactive',
  'somebody-that-i-used-to-know',
  'too-sweet',
];
